name: Publish new release
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

env:
  version-regex: ^(3\.15(\.\d+)?|latest)$

jobs:
  scan:
    name: Scan for recent Tags
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.convert.outputs.tags }}

    steps:
      -
        name: Scan Docker Repository
        uses: dhet/scan-docker-tags-action@v1.0.1
        id: scan
        with:
          image: library/alpine
          max-age-minutes: 144000
          username: services1dysnix
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tag-regex: ${{ env.version-regex }}
      -
        name: Convert tags
        uses: actions/github-script@v5
        id: convert
        with:
          script: |
            core.setOutput('tags', '${{ steps.scan.outputs.tags }}'.replace(/,/g, '\n'))

  push:
    name: Docker Image
    uses: dysnix/github-workflows/.github/workflows/docker.build-and-push.yaml@main
    needs: [scan]
    if: github.event_name == 'worfklow_dispatch' || needs.scan.outputs.tags != ''
    with:
      username: services1dysnix
      push: true
      metadata-tags: |
        ${{ needs.scan.outputs.tags }}
        ${{ github.event_name == 'worfklow_dispatch' && 'latest' || '' }}

    secrets:
      password: "${{ secrets.DOCKERHUB_TOKEN }}"
